#include "PluginEditor.h"
VelvetAudioProcessorEditor::VelvetAudioProcessorEditor(VelvetAudioProcessor& p)
    : AudioProcessorEditor(&p), processorRef(p),
      att_INPUT_GAIN(processorRef.apvts,"INPUT_GAIN",knob_INPUT_GAIN),
      att_DELAY_DELAY_MS_FOK0(processorRef.apvts,"DELAY_DELAY_MS_FOK0",knob_DELAY_DELAY_MS_FOK0),
      att_DELAY_FEEDBACK_FOK0(processorRef.apvts,"DELAY_FEEDBACK_FOK0",knob_DELAY_FEEDBACK_FOK0),
      att_DELAY_MIX_FOK0(processorRef.apvts,"DELAY_MIX_FOK0",knob_DELAY_MIX_FOK0),
      att_GAIN_GAIN_DB_P65U(processorRef.apvts,"GAIN_GAIN_DB_P65U",knob_GAIN_GAIN_DB_P65U),
      att_COMPRESSOR_THRESHOLD_EFNO(processorRef.apvts,"COMPRESSOR_THRESHOLD_EFNO",knob_COMPRESSOR_THRESHOLD_EFNO),
      att_COMPRESSOR_RATIO_EFNO(processorRef.apvts,"COMPRESSOR_RATIO_EFNO",knob_COMPRESSOR_RATIO_EFNO),
      att_COMPRESSOR_ATTACK_EFNO(processorRef.apvts,"COMPRESSOR_ATTACK_EFNO",knob_COMPRESSOR_ATTACK_EFNO),
      att_COMPRESSOR_RELEASE_EFNO(processorRef.apvts,"COMPRESSOR_RELEASE_EFNO",knob_COMPRESSOR_RELEASE_EFNO),
      att_COMPRESSOR_MAKEUP_EFNO(processorRef.apvts,"COMPRESSOR_MAKEUP_EFNO",knob_COMPRESSOR_MAKEUP_EFNO),
      att_BASSBOOSTER_FREQ_L9J7(processorRef.apvts,"BASSBOOSTER_FREQ_L9J7",knob_BASSBOOSTER_FREQ_L9J7),
      att_BASSBOOSTER_GAIN_L9J7(processorRef.apvts,"BASSBOOSTER_GAIN_L9J7",knob_BASSBOOSTER_GAIN_L9J7),
      att_BASSBOOSTER_DRIVE_L9J7(processorRef.apvts,"BASSBOOSTER_DRIVE_L9J7",knob_BASSBOOSTER_DRIVE_L9J7),
      att_STEREOWIDTH_WIDTH_633U(processorRef.apvts,"STEREOWIDTH_WIDTH_633U",knob_STEREOWIDTH_WIDTH_633U),
      att_BITCRUSHER_BITS_9PAI(processorRef.apvts,"BITCRUSHER_BITS_9PAI",knob_BITCRUSHER_BITS_9PAI),
      att_BITCRUSHER_DOWNSAMP_9PAI(processorRef.apvts,"BITCRUSHER_DOWNSAMP_9PAI",knob_BITCRUSHER_DOWNSAMP_9PAI),
      att_OUTPUT_GAIN(processorRef.apvts,"OUTPUT_GAIN",knob_OUTPUT_GAIN)
{
    setLookAndFeel(&lnf); setSize(520,616);
    knob_INPUT_GAIN.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_INPUT_GAIN.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_INPUT_GAIN.setLookAndFeel(&lnf); knob_INPUT_GAIN.setDoubleClickReturnValue(true,0.0f); addAndMakeVisible(knob_INPUT_GAIN); lbl_INPUT_GAIN.setText("INPUT",juce::dontSendNotification); lbl_INPUT_GAIN.setJustificationType(juce::Justification::centred); lbl_INPUT_GAIN.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_INPUT_GAIN.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_INPUT_GAIN);
    knob_DELAY_DELAY_MS_FOK0.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_DELAY_DELAY_MS_FOK0.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_DELAY_DELAY_MS_FOK0.setLookAndFeel(&lnf); knob_DELAY_DELAY_MS_FOK0.setDoubleClickReturnValue(true,250.0f); addAndMakeVisible(knob_DELAY_DELAY_MS_FOK0); lbl_DELAY_DELAY_MS_FOK0.setText("DELAY TIME",juce::dontSendNotification); lbl_DELAY_DELAY_MS_FOK0.setJustificationType(juce::Justification::centred); lbl_DELAY_DELAY_MS_FOK0.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_DELAY_DELAY_MS_FOK0.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_DELAY_DELAY_MS_FOK0);
    knob_DELAY_FEEDBACK_FOK0.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_DELAY_FEEDBACK_FOK0.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_DELAY_FEEDBACK_FOK0.setLookAndFeel(&lnf); knob_DELAY_FEEDBACK_FOK0.setDoubleClickReturnValue(true,40.0f); addAndMakeVisible(knob_DELAY_FEEDBACK_FOK0); lbl_DELAY_FEEDBACK_FOK0.setText("DELAY FEEDBACK",juce::dontSendNotification); lbl_DELAY_FEEDBACK_FOK0.setJustificationType(juce::Justification::centred); lbl_DELAY_FEEDBACK_FOK0.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_DELAY_FEEDBACK_FOK0.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_DELAY_FEEDBACK_FOK0);
    knob_DELAY_MIX_FOK0.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_DELAY_MIX_FOK0.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_DELAY_MIX_FOK0.setLookAndFeel(&lnf); knob_DELAY_MIX_FOK0.setDoubleClickReturnValue(true,30.0f); addAndMakeVisible(knob_DELAY_MIX_FOK0); lbl_DELAY_MIX_FOK0.setText("DELAY MIX",juce::dontSendNotification); lbl_DELAY_MIX_FOK0.setJustificationType(juce::Justification::centred); lbl_DELAY_MIX_FOK0.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_DELAY_MIX_FOK0.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_DELAY_MIX_FOK0);
    knob_GAIN_GAIN_DB_P65U.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_GAIN_GAIN_DB_P65U.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_GAIN_GAIN_DB_P65U.setLookAndFeel(&lnf); knob_GAIN_GAIN_DB_P65U.setDoubleClickReturnValue(true,0.0f); addAndMakeVisible(knob_GAIN_GAIN_DB_P65U); lbl_GAIN_GAIN_DB_P65U.setText("GAIN GAIN",juce::dontSendNotification); lbl_GAIN_GAIN_DB_P65U.setJustificationType(juce::Justification::centred); lbl_GAIN_GAIN_DB_P65U.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_GAIN_GAIN_DB_P65U.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_GAIN_GAIN_DB_P65U);
    knob_COMPRESSOR_THRESHOLD_EFNO.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_COMPRESSOR_THRESHOLD_EFNO.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_COMPRESSOR_THRESHOLD_EFNO.setLookAndFeel(&lnf); knob_COMPRESSOR_THRESHOLD_EFNO.setDoubleClickReturnValue(true,-18.0f); addAndMakeVisible(knob_COMPRESSOR_THRESHOLD_EFNO); lbl_COMPRESSOR_THRESHOLD_EFNO.setText("COMPRESSOR THRESHOLD",juce::dontSendNotification); lbl_COMPRESSOR_THRESHOLD_EFNO.setJustificationType(juce::Justification::centred); lbl_COMPRESSOR_THRESHOLD_EFNO.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_COMPRESSOR_THRESHOLD_EFNO.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_COMPRESSOR_THRESHOLD_EFNO);
    knob_COMPRESSOR_RATIO_EFNO.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_COMPRESSOR_RATIO_EFNO.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_COMPRESSOR_RATIO_EFNO.setLookAndFeel(&lnf); knob_COMPRESSOR_RATIO_EFNO.setDoubleClickReturnValue(true,4.0f); addAndMakeVisible(knob_COMPRESSOR_RATIO_EFNO); lbl_COMPRESSOR_RATIO_EFNO.setText("COMPRESSOR RATIO",juce::dontSendNotification); lbl_COMPRESSOR_RATIO_EFNO.setJustificationType(juce::Justification::centred); lbl_COMPRESSOR_RATIO_EFNO.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_COMPRESSOR_RATIO_EFNO.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_COMPRESSOR_RATIO_EFNO);
    knob_COMPRESSOR_ATTACK_EFNO.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_COMPRESSOR_ATTACK_EFNO.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_COMPRESSOR_ATTACK_EFNO.setLookAndFeel(&lnf); knob_COMPRESSOR_ATTACK_EFNO.setDoubleClickReturnValue(true,10.0f); addAndMakeVisible(knob_COMPRESSOR_ATTACK_EFNO); lbl_COMPRESSOR_ATTACK_EFNO.setText("COMPRESSOR ATTACK",juce::dontSendNotification); lbl_COMPRESSOR_ATTACK_EFNO.setJustificationType(juce::Justification::centred); lbl_COMPRESSOR_ATTACK_EFNO.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_COMPRESSOR_ATTACK_EFNO.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_COMPRESSOR_ATTACK_EFNO);
    knob_COMPRESSOR_RELEASE_EFNO.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_COMPRESSOR_RELEASE_EFNO.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_COMPRESSOR_RELEASE_EFNO.setLookAndFeel(&lnf); knob_COMPRESSOR_RELEASE_EFNO.setDoubleClickReturnValue(true,150.0f); addAndMakeVisible(knob_COMPRESSOR_RELEASE_EFNO); lbl_COMPRESSOR_RELEASE_EFNO.setText("COMPRESSOR RELEASE",juce::dontSendNotification); lbl_COMPRESSOR_RELEASE_EFNO.setJustificationType(juce::Justification::centred); lbl_COMPRESSOR_RELEASE_EFNO.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_COMPRESSOR_RELEASE_EFNO.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_COMPRESSOR_RELEASE_EFNO);
    knob_COMPRESSOR_MAKEUP_EFNO.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_COMPRESSOR_MAKEUP_EFNO.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_COMPRESSOR_MAKEUP_EFNO.setLookAndFeel(&lnf); knob_COMPRESSOR_MAKEUP_EFNO.setDoubleClickReturnValue(true,0.0f); addAndMakeVisible(knob_COMPRESSOR_MAKEUP_EFNO); lbl_COMPRESSOR_MAKEUP_EFNO.setText("COMPRESSOR MAKEUP",juce::dontSendNotification); lbl_COMPRESSOR_MAKEUP_EFNO.setJustificationType(juce::Justification::centred); lbl_COMPRESSOR_MAKEUP_EFNO.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_COMPRESSOR_MAKEUP_EFNO.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_COMPRESSOR_MAKEUP_EFNO);
    knob_BASSBOOSTER_FREQ_L9J7.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_BASSBOOSTER_FREQ_L9J7.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_BASSBOOSTER_FREQ_L9J7.setLookAndFeel(&lnf); knob_BASSBOOSTER_FREQ_L9J7.setDoubleClickReturnValue(true,120.0f); addAndMakeVisible(knob_BASSBOOSTER_FREQ_L9J7); lbl_BASSBOOSTER_FREQ_L9J7.setText("BASS BOOST FREQ",juce::dontSendNotification); lbl_BASSBOOSTER_FREQ_L9J7.setJustificationType(juce::Justification::centred); lbl_BASSBOOSTER_FREQ_L9J7.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_BASSBOOSTER_FREQ_L9J7.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_BASSBOOSTER_FREQ_L9J7);
    knob_BASSBOOSTER_GAIN_L9J7.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_BASSBOOSTER_GAIN_L9J7.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_BASSBOOSTER_GAIN_L9J7.setLookAndFeel(&lnf); knob_BASSBOOSTER_GAIN_L9J7.setDoubleClickReturnValue(true,6.0f); addAndMakeVisible(knob_BASSBOOSTER_GAIN_L9J7); lbl_BASSBOOSTER_GAIN_L9J7.setText("BASS BOOST BOOST",juce::dontSendNotification); lbl_BASSBOOSTER_GAIN_L9J7.setJustificationType(juce::Justification::centred); lbl_BASSBOOSTER_GAIN_L9J7.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_BASSBOOSTER_GAIN_L9J7.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_BASSBOOSTER_GAIN_L9J7);
    knob_BASSBOOSTER_DRIVE_L9J7.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_BASSBOOSTER_DRIVE_L9J7.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_BASSBOOSTER_DRIVE_L9J7.setLookAndFeel(&lnf); knob_BASSBOOSTER_DRIVE_L9J7.setDoubleClickReturnValue(true,20.0f); addAndMakeVisible(knob_BASSBOOSTER_DRIVE_L9J7); lbl_BASSBOOSTER_DRIVE_L9J7.setText("BASS BOOST DRIVE",juce::dontSendNotification); lbl_BASSBOOSTER_DRIVE_L9J7.setJustificationType(juce::Justification::centred); lbl_BASSBOOSTER_DRIVE_L9J7.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_BASSBOOSTER_DRIVE_L9J7.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_BASSBOOSTER_DRIVE_L9J7);
    knob_STEREOWIDTH_WIDTH_633U.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_STEREOWIDTH_WIDTH_633U.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_STEREOWIDTH_WIDTH_633U.setLookAndFeel(&lnf); knob_STEREOWIDTH_WIDTH_633U.setDoubleClickReturnValue(true,120.0f); addAndMakeVisible(knob_STEREOWIDTH_WIDTH_633U); lbl_STEREOWIDTH_WIDTH_633U.setText("WIDTH WIDTH",juce::dontSendNotification); lbl_STEREOWIDTH_WIDTH_633U.setJustificationType(juce::Justification::centred); lbl_STEREOWIDTH_WIDTH_633U.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_STEREOWIDTH_WIDTH_633U.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_STEREOWIDTH_WIDTH_633U);
    knob_BITCRUSHER_BITS_9PAI.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_BITCRUSHER_BITS_9PAI.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_BITCRUSHER_BITS_9PAI.setLookAndFeel(&lnf); knob_BITCRUSHER_BITS_9PAI.setDoubleClickReturnValue(true,8.0f); addAndMakeVisible(knob_BITCRUSHER_BITS_9PAI); lbl_BITCRUSHER_BITS_9PAI.setText("BIT CRUSH BIT DEPTH",juce::dontSendNotification); lbl_BITCRUSHER_BITS_9PAI.setJustificationType(juce::Justification::centred); lbl_BITCRUSHER_BITS_9PAI.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_BITCRUSHER_BITS_9PAI.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_BITCRUSHER_BITS_9PAI);
    knob_BITCRUSHER_DOWNSAMP_9PAI.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_BITCRUSHER_DOWNSAMP_9PAI.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_BITCRUSHER_DOWNSAMP_9PAI.setLookAndFeel(&lnf); knob_BITCRUSHER_DOWNSAMP_9PAI.setDoubleClickReturnValue(true,1.0f); addAndMakeVisible(knob_BITCRUSHER_DOWNSAMP_9PAI); lbl_BITCRUSHER_DOWNSAMP_9PAI.setText("BIT CRUSH DOWNSAMPLE",juce::dontSendNotification); lbl_BITCRUSHER_DOWNSAMP_9PAI.setJustificationType(juce::Justification::centred); lbl_BITCRUSHER_DOWNSAMP_9PAI.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_BITCRUSHER_DOWNSAMP_9PAI.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_BITCRUSHER_DOWNSAMP_9PAI);
    knob_OUTPUT_GAIN.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_OUTPUT_GAIN.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_OUTPUT_GAIN.setLookAndFeel(&lnf); knob_OUTPUT_GAIN.setDoubleClickReturnValue(true,0.0f); addAndMakeVisible(knob_OUTPUT_GAIN); lbl_OUTPUT_GAIN.setText("OUTPUT",juce::dontSendNotification); lbl_OUTPUT_GAIN.setJustificationType(juce::Justification::centred); lbl_OUTPUT_GAIN.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_OUTPUT_GAIN.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_OUTPUT_GAIN);
}
VelvetAudioProcessorEditor::~VelvetAudioProcessorEditor() { setLookAndFeel(nullptr); }
void VelvetAudioProcessorEditor::paint(juce::Graphics& g) {
    g.fillAll(juce::Colour(0xff080e1a));
    g.setColour(juce::Colour(0xff0d1628)); g.fillRect(0,0,520,44);
    g.setColour(juce::Colour(0xff38bdf8).withAlpha(0.2f)); g.fillRect(0,43,520,1);
    g.setColour(juce::Colour(0xffe8eaf0).withAlpha(0.4f)); g.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),11.0f,juce::Font::bold));
    g.drawText("ARCHERGATE",14,0,520-28,44,juce::Justification::centredLeft,false);
    g.setColour(juce::Colour(0xff38bdf8)); g.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),15.0f,juce::Font::bold));
    g.drawText("VELVET",14,0,520-28,44,juce::Justification::centredRight,false);
}
void VelvetAudioProcessorEditor::resized() {
    knob_INPUT_GAIN.setBounds(24,60,112,86); lbl_INPUT_GAIN.setBounds(20,146,120,14);
    knob_DELAY_DELAY_MS_FOK0.setBounds(144,60,112,86); lbl_DELAY_DELAY_MS_FOK0.setBounds(140,146,120,14);
    knob_DELAY_FEEDBACK_FOK0.setBounds(264,60,112,86); lbl_DELAY_FEEDBACK_FOK0.setBounds(260,146,120,14);
    knob_DELAY_MIX_FOK0.setBounds(384,60,112,86); lbl_DELAY_MIX_FOK0.setBounds(380,146,120,14);
    knob_GAIN_GAIN_DB_P65U.setBounds(24,168,112,86); lbl_GAIN_GAIN_DB_P65U.setBounds(20,254,120,14);
    knob_COMPRESSOR_THRESHOLD_EFNO.setBounds(144,168,112,86); lbl_COMPRESSOR_THRESHOLD_EFNO.setBounds(140,254,120,14);
    knob_COMPRESSOR_RATIO_EFNO.setBounds(264,168,112,86); lbl_COMPRESSOR_RATIO_EFNO.setBounds(260,254,120,14);
    knob_COMPRESSOR_ATTACK_EFNO.setBounds(384,168,112,86); lbl_COMPRESSOR_ATTACK_EFNO.setBounds(380,254,120,14);
    knob_COMPRESSOR_RELEASE_EFNO.setBounds(24,276,112,86); lbl_COMPRESSOR_RELEASE_EFNO.setBounds(20,362,120,14);
    knob_COMPRESSOR_MAKEUP_EFNO.setBounds(144,276,112,86); lbl_COMPRESSOR_MAKEUP_EFNO.setBounds(140,362,120,14);
    knob_BASSBOOSTER_FREQ_L9J7.setBounds(264,276,112,86); lbl_BASSBOOSTER_FREQ_L9J7.setBounds(260,362,120,14);
    knob_BASSBOOSTER_GAIN_L9J7.setBounds(384,276,112,86); lbl_BASSBOOSTER_GAIN_L9J7.setBounds(380,362,120,14);
    knob_BASSBOOSTER_DRIVE_L9J7.setBounds(24,384,112,86); lbl_BASSBOOSTER_DRIVE_L9J7.setBounds(20,470,120,14);
    knob_STEREOWIDTH_WIDTH_633U.setBounds(144,384,112,86); lbl_STEREOWIDTH_WIDTH_633U.setBounds(140,470,120,14);
    knob_BITCRUSHER_BITS_9PAI.setBounds(264,384,112,86); lbl_BITCRUSHER_BITS_9PAI.setBounds(260,470,120,14);
    knob_BITCRUSHER_DOWNSAMP_9PAI.setBounds(384,384,112,86); lbl_BITCRUSHER_DOWNSAMP_9PAI.setBounds(380,470,120,14);
    knob_OUTPUT_GAIN.setBounds(24,492,112,86); lbl_OUTPUT_GAIN.setBounds(20,578,120,14);
}
